experimart:
    default:
        data_folder: /tmp/
        data_settings:
            iterator_class: ${$hooknet.iterator.batchiterator.HookNetBatchIterator}
            buffer_dtype: 'uint8'
            user_config:
                wholeslidedata:
                    default:
                        seed: 123
                        data_folder: /tmp/
                        yaml_source: data.yml
                        image_backend: asap
                        labels: 
                            tumor: 1
                            stroma: 2
                            lymphocytes: 3
                        batch_shape: 
                            batch_size: 24
                            spacing: [0.5, 2.0, 8.0]
                            shape: [[284, 284, 3], [284, 284, 3], [284, 284, 3]]
                            y_shape: [3, 70, 70]
                        sample_callbacks:
                            - "*object": wholeslidedata.samplers.callbacks.CropSampleCallback
                              output_shape: [70, 70]
        model@replace(true):
            "*object": experimart.interoperability.torch.io.to_cuda
            model:
                "*object": hooknet.models.torchmodel.HookNet
                n_classes: 4
                depth: 4
                n_convs: 2
                n_filters: 24
                batch_norm: True
        multi_inputs: True
        validation_step_iterator:
          metrics: 
            cm:
              "*object": experimart.interoperability.torch.metrics.TorchConfusionMatrixMetric
              labels: ${validation_data_iterator.dataset.labels.map}
          multi_inputs: ${multi_inputs}
        metrics:
          validation:
            cm: 
              "*object": experimart.interoperability.torch.metrics.TorchConfusionMatrixMetricCollector
              metric: "F1"