experimart:
    default:
        data_folder: /tmp/
        data_settings:
            iterator_class: ${$hooknet.training.iterator.batchiterator.HookNetBatchIterator}
            buffer_dtype: 'uint8'
            user_config:
                wholeslidedata:
                    default:
                        seed: 123
                        data_folder: /tmp/
                        yaml_source: data.yml
                        image_backend: asap
                        labels: 
                            lymphocytes: 1
                            tumor: 2
                            stroma: 3
                        batch_shape: 
                            batch_size: 8
                            spacing: [0.5, 8.0]
                            shape: [[284, 284, 3], [284, 284, 3]]
                            y_shape: [3, 70, 70, ${num_classes}]
                        sample_callbacks:
                            - "*object": wholeslidedata.samplers.callbacks.CropSampleCallback
                              output_shape: [70, 70]
                            - "*object": wholeslidedata.samplers.callbacks.OneHotEncodingSampleCallback
                              labels: ${dataset.labels}

        model@replace(true):        
            "*object": hooknet.models.tensorflowmodel.HookNet
            n_classes: 4
            depth: 4
            n_convs: 2
            n_filters: 8
            batch_norm: True