wholeslidedata:
    default:
        seed: 123
        yaml_source: data.yml

        labels: 
            tumor: 1
            stroma: 2
            lymphocytes: 3

        batch_shape:
            batch_size: 1
            shape: [[1244,1244,3],[1244,1244,3], [1244,1244,3]]
            spacing: [0.5, 2.0, 8.0]
            y_shape: [3, 1030, 1030]

        sample_callbacks:
            - "*object": wholeslidedata.samplers.callbacks.CropSampleCallback
              output_shape: [1030, 1030]