default:
  project: HookNet-TIGER
  log_path: '/tmp/'
  cpus: 4
  epochs: 200
  steps: 50
  learning_rate: 0.05
  model: None
  model_parameters:
    "*object": hooknet.model_torch.get_parameters
    model: ${model}
  criterion:
    "*object": torch.nn.CrossEntropyLoss
    ignore_index: 0
  optimizer:
    '*object': torch.optim.Adam
    params: ${model_parameters}
    lr: ${learning_rate}
  scheduler:
    '*object': torch.optim.lr_scheduler.ExponentialLR
    optimizer: ${optimizer}
    gamma: 0.9