wholeslidedata:
  default:
    seed: 123
    data_folder: /tmp/
    yaml_source: hooknetdata.yml
    image_backend: asap
    labels: 
      lymphocytes: 1
      tumor: 2
      stroma: 3
    batch_shape: 
      batch_size: 1
      spacing: [0.5, 2.0, 8.0]
      shape: [[1244, 1244, 3], [1244, 1244, 3], [1244, 1244, 3]]
      y_shape: [3, 1030, 1030]
    sample_callbacks:
      - "*object": wholeslidedata.samplers.callbacks.CropSampleCallback
        output_shape: [1030, 1030]
      - "*object": wholeslidedata.samplers.callbacks.NormalizeSampleCallback
        