experimart:
    default:
        data_folder: /tmp/
        data_settings:
            user_config:
                wholeslidedata:
                    default:
                        seed: 123
                        data_folder: /tmp/
                        yaml_source: data.yml
                        image_backend: asap
                        labels: 
                            lymphocytes: 1
                            tumor: 2
                            stroma: 3
                        batch_shape: 
                            batch_size: 8
                            spacing: [0.5, 2.0, 8.0]
                            shape: [[284, 284, 3], [284, 284, 3], [284, 284, 3]]
                            y_shape: [3, 70, 70]
                        sample_callbacks:
                            - "*object": wholeslidedata.samplers.callbacks.CropSampleCallback
                              output_shape: [70, 70]
                            - "*object": wholeslidedata.samplers.callbacks.NormalizeSampleCallback
        model@replace(true):
            "*object": experimart.interoperability.torch.io.to_cuda
            model:
                "*object": hooknet.torchmodel.HookNet
                n_classes: 4
                depth: 4
                n_convs: 2
                n_filters: 8
                batch_norm: True
        training_step_iterator:
            "*object": hooknet.training.torchstep.HookNetTorchTrainingStepIterator
        validation_step_iterator:
            "*object": hooknet.training.torchstep.HookNetTorchValidationStepIterator
