experimart:
    default:
      data_folder: /tmp/
      
      data_settings:
        user_config: iteratoruserconfig.yml
        iterator_class: ${$wholeslidedata.interoperability.pytorch.iterator.TorchBatchIterator}
 
      model@replace(true):
        "*object": experimart.interoperability.torch.io.to_cuda
        model:
            "*object": hooknet.model_torch.HookNet
            n_classes: 4
            depth: 4
            n_convs: 2
            n_filters: 8
            batch_norm: True

      training_step_iterator:
        "*object": hooknet.training.step.HookNetTorchTrainingStepIterator

      validation_step_iterator:
        "*object": hooknet.training.step.HookNetTorchValidationStepIterator
        
